/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * ZKBridge API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateMinterOrderDto {
  recipient: string;
  sender: string;
  sentAmount: string;
  srcTxHash: string;
}
