/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * ZKBridge API
 * OpenAPI spec version: 1.0.0
 */

export interface ReadRewardsDto {
  earner: string;
  id: number;
  pendingClaimed: string;
  rewardToken: string;
  totalClaimed: string;
}
