/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * ZKBridge API
 * OpenAPI spec version: 1.0.0
 */

export interface ReadMinterOrderDto {
  created_at: string;
  dstTxHash: string;
  receivedAmount: string;
  recipient: string;
  sender: string;
  sentAmount: string;
  srcTxHash: string;
}
